In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
# 1) Load the cleaned dataset
df = pd.read_csv("housing_price.csv")

In [4]:
df.head(20)

,Size_sqft,Bedrooms,Bathrooms,YearBuilt,Price,Location_City,Location_Rural,Location_Suburb,HouseAge,Rooms_per_1000sqft,Size_per_Bedroom,Is_City,LogPrice
0,1.030281,-1.463643,0.088986,-1.279342,812100.0,1,0,0,1.279342,-1.061465,3.123085,1,13.607380
1,-0.482463,-1.463643,1.347506,1.326476,547000.0,1,0,0,-1.326476,-0.265637,1.309520,1,13.212206
2,0.468877,0.007430,-1.169534,-1.339942,693700.0,1,0,0,1.339942,-0.689547,-0.163970,1,13.449796
3,1.079817,0.742966,1.347506,-0.915740,848300.0,1,0,0,0.915740,-0.199111,-0.307614,1,13.650991
4,0.788954,1.478502,-1.169534,0.962873,806000.0,0,0,1,-0.962873,-0.311002,-0.610027,0,13.599840
5,0.881674,0.007430,-1.169534,-1.339942,724400.0,1,0,0,1.339942,-0.805365,0.000992,1,13.493100
6,1.280500,1.478502,0.088986,-0.612737,715100.0,0,0,1,0.612737,-0.274025,-0.492168,0,13.480179
7,-0.266538,0.742966,-1.169534,-0.733938,547900.0,0,0,1,0.733938,-0.056450,-0.711136,0,13.213850
8,-0.802540,-0.728107,0.088986,-1.339942,516700.0,0,0,1,1.339942,-0.032310,-0.272591,0,13.155220
9,-1.263604,0.742966,1.347506,-1.036940,418600.0,1,0,0,1.036940,2.122592,-1.009971,1,12.944673
10,0.794034,0.007430,0.088986,1.023474,654200.0,1,0,0,-1.023474,-0.547998,-0.034031,1,13.391170
11,0.782603,-0.728107,0.088986,-1.521744,715100.0,1,0,0,1.521744,-0.780002,0.677589,1,13.480179
12,-0.253837,-0.728107,-1.169534,-0.612737,573400.0,1,0,0,0.612737,-0.728057,0.056317,1,13.259341
13,0.703854,0.007430,1.347506,1.084074,867000.0,1,0,0,-1.084074,-0.276725,-0.070069,1,13.672795
14,1.046793,-0.728107,0.088986,1.084074,599600.0,1,0,0,-1.084074,-0.844736,0.835953,1,13.304020
15,-0.328776,-1.463643,1.347506,-0.249135,543800.0,0,0,1,0.249135,-0.356207,1.493770,0,13.206339
16,1.556122,0.742966,1.347506,0.781072,857800.0,0,1,0,-0.781072,-0.365669,-0.164858,0,13.662127
17,-0.595506,-1.463643,0.088986,-0.855139,501100.0,1,0,0,0.855139,-0.573974,1.173998,1,13.124563
18,-0.134443,0.007430,-1.169534,-0.491537,554800.0,1,0,0,0.491537,-0.455788,-0.405068,1,13.226365
19,1.073466,-0.728107,0.088986,-0.127934,761200.0,1,0,0,0.127934,-0.850781,0.851941,1,13.542653

In [14]:
# 2) Split features (X) and target (y)
X = df.drop(columns=["Price", "LogPrice"])
y = df["Price"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
# 4) Train Linear Regression
# --------------------------------
# Linear model is simple and interpretable; good baseline.
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

In [9]:
# 5) Train Random Forest
# --------------------------------
# Ensemble model captures non-linear relationships; often stronger than linear.
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

In [10]:
# 6) Helper to print metrics nicely
# --------------------------------
def print_metrics(name, y_true, y_pred):
    """Print R², MAE, MSE, RMSE for a model's predictions."""
    r2  = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    print(f"\n{name} Performance:")
    print(f"  R²   : {r2:.3f}")          # higher is better (max = 1.0)
    print(f"  MAE  : {mae:,.0f}")        # lower is better (absolute error)
    print(f"  MSE  : {mse:,.0f}")        # lower is better (squared error)
    print(f"  RMSE : {rmse:,.0f}")       # lower is better (same units as Price)

In [11]:
# 7) Show results for both models
# --------------------------------
print_metrics("Linear Regression", y_test, lr_pred)
print_metrics("Random Forest",   y_test, rf_pred)

Linear Regression Performance:
  R²   : 0.848
  MAE  : 63,086
  MSE  : 5,718,940,941
  RMSE : 75,624

Random Forest Performance:
  R²   : 0.859
  MAE  : 52,524
  MSE  : 5,283,317,455
  RMSE : 72,686

In [12]:
# 8) Single-row prediction (sanity check)

i = 3
x_one_df = X_test.iloc[[i]]   # 1-row DataFrame (keeps feature names)
y_true   = y_test.iloc[i]     # scalar

p_lr_one = float(lr.predict(x_one_df)[0])
p_rf_one = float(rf.predict(x_one_df)[0])

print("\nSingle-row sanity check:")
print(f"  Actual Price: ${y_true:,.0f}")
print(f"  LR Pred     : ${p_lr_one:,.0f}")
print(f"  RF Pred     : ${p_rf_one:,.0f}")

Single-row sanity check:
  Actual Price: $554,800
  LR Pred     : $594,041
  RF Pred     : $557,028